/**
 * InterventionCard — 02_FRONTEND_CONTRACT.md §5.5.
 *
 * The rules that make the demo's key frame work:
 *  - `certificate.verdict === "UNSTABLE"` -> `opacity-70`, red left border, and
 *    the title **struck through**. Approve stays enabled (the operator may
 *    override) but is styled secondary.
 *  - `certificate.reason` renders **verbatim**. It was generated by the solver,
 *    not the LLM, and rewriting it here would be inventing analysis.
 *  - The compliance sweep is exactly three fixed cells: 40% / 60% / 90%.
 */
import { useState } from 'react';
import {
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  Shield,
  ChevronDown,
  ChevronRight,
  Check,
  X,
  AlertTriangle,
  Info,
  TrendingDown
} from 'lucide-react';

import { verdictStyle } from '../lib/colors.js';
import { decimals, minutes, pct, rupees } from '../lib/format.js';

function VerdictBadge({ verdict }) {
  const style = verdictStyle(verdict);
  const Icon =
    verdict === 'STABLE'
      ? ShieldCheck
      : verdict === 'UNSTABLE'
        ? ShieldX
        : verdict === 'CONDITIONAL'
          ? ShieldAlert
          : Shield;

  return (
    <span
      className="inline-flex items-center gap-1 rounded px-2 py-0.5 text-[10px] font-bold font-mono tracking-wider border shadow-sm"
      style={{
        color: style.hex,
        borderColor: `${style.hex}44`,
        backgroundColor: `${style.hex}14`,
      }}
    >
      <Icon className="h-3 w-3" />
      <span>{style.label}</span>
    </span>
  );
}

function SweepCell({ row }) {
  const style = verdictStyle(row.verdict);
  return (
    <div
      className="rounded border p-2 text-center transition-colors"
      style={{ borderColor: `${style.hex}44`, backgroundColor: `${style.hex}10` }}
    >
      <div className="text-[9px] font-mono uppercase tracking-wider text-slate-400">
        {Math.round(row.compliance_rate * 100)}% Compliance
      </div>
      <div className="mt-0.5 text-xs font-bold tabular-nums text-slate-100">
        {Math.round(row.max_utilisation * 100)}% Max Load
      </div>
      <div className="text-[9px] font-bold font-mono uppercase mt-0.5" style={{ color: style.hex }}>
        {row.verdict}
      </div>
    </div>
  );
}

function CertificateDetail({ certificate }) {
  return (
    <div className="mt-2.5 space-y-2.5 rounded border border-surface-700/80 bg-surface-950/80 p-2.5 font-mono text-[10px]">
      <div className="text-[9px] font-bold uppercase tracking-wider text-slate-400">
        Game-Theoretic Compliance Sweep
      </div>
      <div className="grid grid-cols-3 gap-1.5">
        {certificate.compliance_sweep.map((row) => (
          <SweepCell key={row.compliance_rate} row={row} />
        ))}
      </div>

      <dl className="grid grid-cols-2 gap-x-4 gap-y-1.5 pt-1.5 border-t border-surface-800">
        <div className="flex justify-between">
          <dt className="text-slate-400 font-sans">Baseline Variance</dt>
          <dd className="tabular-nums text-slate-200">
            {decimals(certificate.baseline_variance, 3)}
          </dd>
        </div>
        <div className="flex justify-between">
          <dt className="text-slate-400 font-sans">Post-nudge Variance</dt>
          <dd
            className={`tabular-nums font-semibold ${
              certificate.post_nudge_variance > certificate.baseline_variance
                ? 'text-red-400'
                : 'text-emerald-400'
            }`}
          >
            {decimals(certificate.post_nudge_variance, 3)}
          </dd>
        </div>
        <div className="flex justify-between">
          <dt className="text-slate-400 font-sans">Oscillation Risk</dt>
          <dd className={certificate.oscillation_risk ? 'text-red-400 font-bold' : 'text-slate-300'}>
            {certificate.oscillation_risk ? 'YES (HIGH)' : 'NONE'}
          </dd>
        </div>
        <div className="flex justify-between">
          <dt className="text-slate-400 font-sans">Solver Convergence</dt>
          <dd className={certificate.converged ? 'text-emerald-400' : 'text-red-400'}>
            {certificate.converged ? `YES (${certificate.iterations} iters)` : 'NO'}
          </dd>
        </div>
        <div className="flex justify-between">
          <dt className="text-slate-400 font-sans">Peak Bottleneck Node</dt>
          <dd className="text-slate-200 truncate max-w-[100px]">{certificate.max_zone_entity_id || '—'}</dd>
        </div>
        <div className="flex justify-between">
          <dt className="text-slate-400 font-sans">Compliance Sensitivity</dt>
          <dd className="tabular-nums text-slate-200">
            {decimals(certificate.compliance_sensitivity, 2)}
          </dd>
        </div>
      </dl>
    </div>
  );
}

/** What simulating this action on a copy of the live city showed. */
function EvaluationStrip({ evaluation, nodesById }) {
  if (!evaluation) return null;
  const name = (id) => nodesById?.[id]?.display_name || id;
  const before = Math.round(evaluation.root_peak_before * 100);
  const after = Math.round(evaluation.root_peak_after * 100);
  return (
    <div className="mt-2 rounded border border-teal-500/25 bg-teal-500/[0.05] p-1.5 text-[10px] leading-relaxed text-slate-300">
      <div className="font-semibold text-teal-800">
        Simulated over {Math.round(evaluation.horizon_sec / 60)} min at {Math.round(evaluation.compliance * 100)}% compliance
      </div>
      <div>
        Peak at {name(evaluation.root_entity_id)}: {before}% → <b className={after < before ? 'text-emerald-700' : 'text-red-600'}>{after}%</b>
        {evaluation.people_redirected > 0 && <> · {evaluation.people_redirected.toLocaleString('en-IN')} visitors redirected</>}
        {evaluation.travel_time_delta_sec !== 0 && (
          <> · trip time {evaluation.travel_time_delta_sec > 0 ? '+' : ''}{Math.round(evaluation.travel_time_delta_sec)}s</>
        )}
      </div>
      {evaluation.new_critical_entities?.length > 0 && (
        <div className="text-red-600">
          Side effect: pushes {evaluation.new_critical_entities.map(name).join(', ')} over the critical line
        </div>
      )}
    </div>
  );
}

export default function InterventionCard({ intervention, onApprove, onReject, busy, nodesById }) {
  const [expanded, setExpanded] = useState(false);
  const certificate = intervention.certificate;
  const unstable = certificate?.verdict === 'UNSTABLE';
  const resolved = intervention.status !== 'proposed';

  // Left border communicates verdict at a glance
  const borderClass = unstable
    ? 'border-l-4 border-l-red-500 opacity-75 bg-red-950/10'
    : certificate?.verdict === 'STABLE'
      ? 'border-l-4 border-l-emerald-500 bg-surface-850/80'
      : certificate?.verdict === 'CONDITIONAL'
        ? 'border-l-4 border-l-amber-500 bg-surface-850/80'
        : 'border-l-4 border-l-surface-650 bg-surface-850/80';

  return (
    <article
      className={`rounded-md border border-surface-700/70 p-3 shadow-panel transition-all select-none ${borderClass}`}
    >
      {/* Top Header: Verdict & Rank Score */}
      <div className="flex items-center justify-between gap-2">
        {certificate ? (
          <VerdictBadge verdict={certificate.verdict} />
        ) : (
          <span className="rounded bg-surface-750 px-2 py-0.5 text-[10px] font-mono text-slate-400">
            CERTIFYING…
          </span>
        )}
        <span className="text-[10px] font-mono font-semibold text-slate-400">
          RANK <span className="text-slate-200">{decimals(intervention.rank_score, 2)}</span>
        </span>
      </div>

      {/* Action Title */}
      <h3
        className={`mt-1.5 text-xs font-semibold leading-snug tracking-tight ${
          unstable ? 'text-slate-400 line-through' : 'text-slate-100'
        }`}
      >
        {intervention.title}
      </h3>

      {/* Structured Metrics Bar */}
      <div className="mt-2 grid grid-cols-4 gap-1 rounded bg-surface-900/60 p-1.5 border border-surface-700/50 text-[10px]">
        <div className="flex flex-col">
          <span className="text-[8px] font-bold uppercase tracking-wider text-slate-400 leading-none">Relief</span>
          <span className="mt-0.5 font-bold font-mono text-emerald-400 leading-none">
            {pct(intervention.estimated_relief_pct)}
          </span>
        </div>
        <div className="flex flex-col border-l border-surface-700/50 pl-1.5">
          <span className="text-[8px] font-bold uppercase tracking-wider text-slate-400 leading-none">Cost</span>
          <span className="mt-0.5 font-mono text-slate-300 leading-none">
            {rupees(intervention.estimated_cost_paise)}
          </span>
        </div>
        <div className="flex flex-col border-l border-surface-700/50 pl-1.5">
          <span className="text-[8px] font-bold uppercase tracking-wider text-slate-400 leading-none">Delay</span>
          <span className="mt-0.5 font-mono text-slate-300 leading-none">
            +{minutes(intervention.estimated_delay_sec)}
          </span>
        </div>
        <div className="flex flex-col border-l border-surface-700/50 pl-1.5">
          <span className="text-[8px] font-bold uppercase tracking-wider text-slate-400 leading-none">Feasibility</span>
          <span className="mt-0.5 font-mono text-teal-400 leading-none">
            {decimals(intervention.feasibility, 2)}
          </span>
        </div>
      </div>

      <p className="mt-1.5 text-[10px] leading-relaxed text-slate-400">{intervention.description}</p>
      <EvaluationStrip evaluation={intervention.evaluation} nodesById={nodesById} />

      {/* Verbatim Certificate Reason from Solver */}
      {certificate && (
        <div
          className={`mt-2 flex items-start gap-1.5 rounded p-1.5 text-[10px] leading-relaxed border ${
            unstable
              ? 'border-red-500/30 bg-red-950/20 text-red-200'
              : 'border-surface-700/50 bg-surface-900/40 text-slate-300'
          }`}
        >
          {unstable ? (
            <AlertTriangle className="h-3 w-3 text-red-400 shrink-0 mt-0.5" />
          ) : (
            <Info className="h-3 w-3 text-teal-400 shrink-0 mt-0.5" />
          )}
          <span>{certificate.reason}</span>
        </div>
      )}

      {/* Expandable Certificate Details */}
      {certificate && (
        <button
          type="button"
          onClick={() => setExpanded((v) => !v)}
          className="mt-2 flex items-center gap-1 text-[10px] font-mono text-slate-400 hover:text-teal-300 transition-colors"
        >
          {expanded ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
          <span>Equilibrium Certificate Details</span>
        </button>
      )}
      {expanded && certificate && <CertificateDetail certificate={certificate} />}

      {/* Action Decision Buttons */}
      <div className="mt-3 flex items-center justify-end gap-2 pt-2 border-t border-surface-700/40">
        {resolved ? (
          <span className="chip border border-surface-700 bg-surface-750 font-mono text-[10px] uppercase text-slate-300">
            {intervention.status}
          </span>
        ) : (
          <>
            <button
              type="button"
              className="btn btn-secondary text-xs h-7 px-3 gap-1 hover:border-red-500/40 hover:text-red-300"
              disabled={busy}
              onClick={() => onReject(intervention)}
              title="Reject candidate intervention"
            >
              <X className="h-3 w-3" />
              <span>Reject</span>
            </button>
            <button
              type="button"
              // Primary action is prominent. UNSTABLE is de-emphasised to secondary.
              className={`btn text-xs h-7 px-3.5 gap-1.5 font-semibold ${
                unstable
                  ? 'btn-secondary text-amber-300 border-amber-500/40 hover:border-amber-500/60'
                  : 'btn-primary'
              }`}
              disabled={busy}
              onClick={() => onApprove(intervention)}
              title="Authorize and dispatch intervention"
            >
              <Check className="h-3.5 w-3.5" />
              <span>Approve Action</span>
            </button>
          </>
        )}
      </div>
    </article>
  );
}
