/**
 * InterventionCard — 02_FRONTEND_CONTRACT.md §5.5.
 *
 * The rules that make the demo's key frame work:
 *
 *  - `certificate.verdict === "UNSTABLE"` -> `opacity-60`, red left border, and
 *    the title **struck through**. Approve stays enabled (the operator may
 *    override) but is styled secondary.
 *  - `certificate.reason` renders **verbatim**. It was generated by the solver,
 *    not the LLM, and rewriting it here would be inventing analysis.
 *  - The compliance sweep is exactly three fixed cells: 40% / 60% / 90%.
 *
 * When a STABLE card and an UNSTABLE card are visible together, the contrast
 * between them is the single most important frame in the presentation.
 */
import { useState } from 'react';

import { verdictStyle } from '../lib/colors.js';
import { decimals, minutes, pct, rupees } from '../lib/format.js';

function VerdictBadge({ verdict }) {
  const style = verdictStyle(verdict);
  return (
    <span
      className="chip border font-semibold"
      style={{ color: style.hex, borderColor: `${style.hex}66`, backgroundColor: `${style.hex}1A` }}
    >
      <span aria-hidden="true">⛨</span>
      {style.label}
    </span>
  );
}

function SweepCell({ row }) {
  const style = verdictStyle(row.verdict);
  return (
    <div
      className="rounded border px-2 py-1.5 text-center"
      style={{ borderColor: `${style.hex}44`, backgroundColor: `${style.hex}12` }}
    >
      <div className="text-[10px] uppercase tracking-wider text-slate-500">
        {Math.round(row.compliance_rate * 100)}% comply
      </div>
      <div className="mt-0.5 text-sm font-semibold tabular-nums text-slate-100">
        {Math.round(row.max_utilisation * 100)}%
      </div>
      <div className="text-[10px] font-medium" style={{ color: style.hex }}>
        {row.verdict}
      </div>
    </div>
  );
}

function CertificateDetail({ certificate }) {
  return (
    <div className="mt-2 space-y-2 rounded-md border border-surface-600 bg-surface-900/60 p-2.5">
      <div className="grid grid-cols-3 gap-2">
        {certificate.compliance_sweep.map((row) => (
          <SweepCell key={row.compliance_rate} row={row} />
        ))}
      </div>
      <dl className="grid grid-cols-2 gap-x-4 gap-y-1 text-[11px]">
        <div className="flex justify-between">
          <dt className="text-slate-500">Baseline variance</dt>
          <dd className="tabular-nums text-slate-300">
            {decimals(certificate.baseline_variance, 3)}
          </dd>
        </div>
        <div className="flex justify-between">
          <dt className="text-slate-500">Post-nudge variance</dt>
          <dd
            className={`tabular-nums ${
              certificate.post_nudge_variance > certificate.baseline_variance
                ? 'text-red-400'
                : 'text-green-400'
            }`}
          >
            {decimals(certificate.post_nudge_variance, 3)}
          </dd>
        </div>
        <div className="flex justify-between">
          <dt className="text-slate-500">Oscillation risk</dt>
          <dd className={certificate.oscillation_risk ? 'text-red-400' : 'text-slate-300'}>
            {certificate.oscillation_risk ? 'yes' : 'no'}
          </dd>
        </div>
        <div className="flex justify-between">
          <dt className="text-slate-500">Converged</dt>
          <dd className={certificate.converged ? 'text-slate-300' : 'text-red-400'}>
            {certificate.converged ? `yes (${certificate.iterations} iters)` : 'no'}
          </dd>
        </div>
        <div className="flex justify-between">
          <dt className="text-slate-500">Peak entity</dt>
          <dd className="text-slate-300">{certificate.max_zone_entity_id || '—'}</dd>
        </div>
        <div className="flex justify-between">
          <dt className="text-slate-500">Compliance sensitivity</dt>
          <dd className="tabular-nums text-slate-300">
            {decimals(certificate.compliance_sensitivity, 2)}
          </dd>
        </div>
      </dl>
    </div>
  );
}

export default function InterventionCard({ intervention, onApprove, onReject, busy }) {
  const [expanded, setExpanded] = useState(false);
  const certificate = intervention.certificate;
  const unstable = certificate?.verdict === 'UNSTABLE';
  const resolved = intervention.status !== 'proposed';

  // Left border communicates verdict at a glance — the contrast between a
  // green STABLE card and a red UNSTABLE card is the key demo moment.
  const borderClass = unstable
    ? 'border-l-red-500 opacity-60'
    : certificate?.verdict === 'STABLE'
      ? 'border-l-green-500/70'
      : certificate?.verdict === 'CONDITIONAL'
        ? 'border-l-yellow-500/60'
        : 'border-l-surface-600';

  return (
    <article
      className={`panel border-l-2 p-3 transition-opacity ${borderClass}`}
    >
      <div className="flex items-start justify-between gap-2">
        {certificate ? (
          <VerdictBadge verdict={certificate.verdict} />
        ) : (
          <span className="chip bg-surface-700 text-slate-400">certifying…</span>
        )}
        <span className="text-[11px] tabular-nums text-slate-500">
          rank {decimals(intervention.rank_score, 2)}
        </span>
      </div>

      <h3
        className={`mt-1.5 text-sm font-semibold leading-snug ${
          unstable ? 'text-slate-400 line-through' : 'text-slate-100'
        }`}
      >
        {intervention.title}
      </h3>

      <div className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-0.5 text-[11px] text-slate-400">
        <span>Relief {pct(intervention.estimated_relief_pct)}</span>
        <span className="text-slate-600">·</span>
        <span>{rupees(intervention.estimated_cost_paise)}</span>
        <span className="text-slate-600">·</span>
        <span>+{minutes(intervention.estimated_delay_sec)}</span>
        <span className="text-slate-600">·</span>
        <span>feasibility {decimals(intervention.feasibility, 2)}</span>
      </div>

      {certificate && (
        // Verbatim from the solver. Never rewritten here.
        <p
          className={`mt-1.5 flex gap-1.5 text-[11px] leading-snug ${
            unstable ? 'text-red-300' : 'text-slate-400'
          }`}
        >
          <span aria-hidden="true">{unstable ? '⚠' : 'ℹ'}</span>
          <span>{certificate.reason}</span>
        </p>
      )}

      {certificate && (
        <button
          type="button"
          onClick={() => setExpanded((v) => !v)}
          className="mt-1.5 text-[11px] text-slate-500 hover:text-slate-300"
        >
          {expanded ? '▾' : '▸'} Certificate detail
        </button>
      )}
      {expanded && certificate && <CertificateDetail certificate={certificate} />}

      <div className="mt-2.5 flex items-center justify-end gap-2">
        {resolved ? (
          <span className="chip bg-surface-700 text-slate-400">{intervention.status}</span>
        ) : (
          <>
            <button
              type="button"
              className="btn-secondary"
              disabled={busy}
              onClick={() => onReject(intervention)}
            >
              Reject
            </button>
            <button
              type="button"
              // Approve stays enabled for an UNSTABLE option — the operator has
              // the authority to override. It is de-emphasised, not disabled.
              className={unstable ? 'btn-secondary' : 'btn-primary'}
              disabled={busy}
              onClick={() => onApprove(intervention)}
            >
              Approve
            </button>
          </>
        )}
      </div>
    </article>
  );
}
