"""The CityModel interface: what the rest of EventFlow relies on from a city simulator.

`SyntheticGenerator` (generator.py, the flow-based model) is the production
implementation. The engine, What-If, candidate evaluation, the look-ahead
projection, accommodation, the event schedule and journey planning all use the
model only through the methods below, so another implementation (a calibrated
model fed by real sensor/booking data, or an ML drop-in at `ML/generator.py`
picked up by `ml_registry`) can replace it without touching those services.

Decision record (kept here so it is not lost): the original per-entity
curve generator was *not* restored as a second implementation. It had no
queues, bookings, event schedule, intervention application or cloning, so
supporting this interface would have meant re-implementing the flow model's
logic on top of curves — duplicate logic with no product value. It remains
recoverable from git history (commit e445d5a, `app/ml_reference/generator.py`).
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class CityModel(Protocol):
    # --- 03 §8.1 contract surface ------------------------------------------------
    def ready(self) -> bool: ...
    def fallback(self, dt_sec: int = 30) -> dict[str, float]: ...
    def tick(self, dt_sec: int = 30) -> dict[str, float]: ...
    def ground_truth(self) -> dict[str, dict[str, Any]]: ...
    def reset(self, seed: int | None = None) -> None: ...
    def seek(self, elapsed_sec: float) -> None: ...

    # --- state ---------------------------------------------------------------------
    def capacity(self, entity_id: str) -> float: ...
    def utilisation(self) -> dict[str, float]: ...
    def queue_delay_sec(self, entity_id: str) -> float: ...
    def closed_entities(self) -> set[str]: ...
    def gates_of_venue(self, venue_id: str) -> list[str]: ...
    def stats(self) -> dict[str, float]: ...
    def properties_state(self) -> list[dict[str, Any]]: ...
    def event_states(self) -> dict[str, dict[str, Any]]: ...

    # --- changes -------------------------------------------------------------------
    def set_events(self, events: list[dict[str, Any]]) -> None: ...
    def inject(self, scenario_type: str, params: dict | None = None, source: str = "disruption",
               modifier_id: str | None = None) -> str: ...
    def remove_modifier(self, modifier_id: str) -> bool: ...
    def apply_intervention(self, intervention: dict, compliance: float, duration_sec: float | None = None) -> str: ...
    def set_compliance(self, compliance: float) -> None: ...

    # --- forking (what-if, evaluation, counterfactuals, twin process model) ----------
    def clone(self, sources: set[str] | None = None) -> "CityModel": ...
