/**
 * Mock mode — 02_FRONTEND_CONTRACT.md §8.
 *
 * These fixtures are generated by the backend itself
 * (`python -m scripts.export_mocks`), so they are the *exact* payloads the real
 * endpoints return and validate against the same JSON Schemas
 * (`npm run validate:mocks`). A mock cannot drift from a contract it was
 * produced by.
 *
 * `startMockDriver` replays `state_sequence.json` on the demo cadence, calling
 * the identical store actions the WebSocket handlers call — so mock mode and
 * live mode exercise the same code path, and the only difference is where the
 * bytes came from.
 */
import graphData from '../mocks/graph.json';
import eventData from '../mocks/event.json';
import stateData from '../mocks/state.json';
import stateSequence from '../mocks/state_sequence.json';
import pressureSequence from '../mocks/pressure_timeline.json';
import cascadeMetroB from '../mocks/cascade_metro_b.json';
import cascadesActive from '../mocks/cascades_active.json';
import interventionsData from '../mocks/interventions.json';
import twinFidelityData from '../mocks/twin_fidelity.json';
import twinSequence from '../mocks/twin_fidelity_sequence.json';
import metricsData from '../mocks/metrics.json';
import regretData from '../mocks/regret.json';
import commanderResponses from '../mocks/commander_responses.json';
import journeyData from '../mocks/attendee_journey.json';
import nudgeData from '../mocks/attendee_nudges.json';
import simulationData from '../mocks/simulation.json';
import healthData from '../mocks/health.json';
import overviewData from '../mocks/overview.json';
import eventsData from '../mocks/events.json';
import hotelsData from '../mocks/hotels.json';
import stayData from '../mocks/stay_recommendation.json';
import saturationData from '../mocks/saturation.json';
import disruptionsData from '../mocks/disruptions.json';

import { advanceMockDriver } from './mockLifecycle.js';

const LATENCY_MS = 120; // enough to exercise the loading states, not enough to annoy

const delay = (value) =>
  new Promise((resolve) => setTimeout(() => resolve(structuredClone(value)), LATENCY_MS));

// Mutable copies so approve/reject behave like the real thing within a session.
let interventionState = structuredClone(interventionsData);
let nudgeState = structuredClone(nudgeData);

export const health = () => delay(healthData);
export const event = () => delay(eventData);
export const graph = () => delay(graphData);
export const state = () => delay(stateData);
export const activeCascades = () => delay(cascadesActive);
export const twinFidelity = () => delay(twinFidelityData);
export const metrics = () => delay(metricsData);
export const regret = () => delay(regretData);
export const interventions = () => delay(interventionState);
export const simulation = () => delay(simulationData);

export const forecast = () =>
  delay({
    generated_at: stateData.sim_time,
    active_source: healthData.modules.forecaster.active_source,
    forecasts: [],
  });

export const pressureTimeline = () => {
  const last = pressureSequence[pressureSequence.length - 1];
  return delay({ sim_time: last.sim_time, items: last.items });
};

export function entity(entityId) {
  const node = graphData.nodes.find((n) => n.entity_id === entityId);
  const entityState = stateData.entities.find((e) => e.entity_id === entityId);
  if (!node || !entityState) {
    return Promise.reject(
      Object.assign(new Error(`No entity with id '${entityId}'.`), {
        code: 'ENTITY_NOT_FOUND',
      }),
    );
  }
  return delay({
    state: entityState,
    forecast: null,
    edges_in: graphData.edges.filter((e) => e.dst_entity_id === entityId),
    edges_out: graphData.edges.filter((e) => e.src_entity_id === entityId),
    risk_breakdown: [
      { risk_type: 'crowd', score: entityState.risk_score },
      { risk_type: 'capacity', score: entityState.risk_score },
      { risk_type: 'cascading', score: Math.round(entityState.risk_score * 0.8) },
      { risk_type: 'overall', score: entityState.risk_score },
    ],
  });
}

export function cascade(entityId) {
  const found =
    cascadesActive.cascades.find((c) => c.root_entity_id === entityId) ||
    (entityId === 'metro_b' ? cascadeMetroB : null);
  return delay(
    found || {
      root_entity_id: entityId,
      source: 'deterministic',
      generated_at: stateData.sim_time,
      total_downstream_failures: 0,
      max_depth: 0,
      steps: [],
    },
  );
}

export function approve(interventionId) {
  const item = interventionState.interventions.find((i) => i.intervention_id === interventionId);
  if (item) item.status = 'executing';
  return delay({
    intervention_id: interventionId,
    status: 'executing',
    applied_at: stateData.sim_time,
    nudges_issued: nudgeState.nudges.length,
    twin_branch_id: 'sim_mock1',
  });
}

export function reject(interventionId) {
  const item = interventionState.interventions.find((i) => i.intervention_id === interventionId);
  if (item) item.status = 'rejected';
  return delay({ intervention_id: interventionId, status: 'rejected' });
}

export const driftMode = (enabled) =>
  delay({
    drift_mode_enabled: enabled,
    uncorrected_ensemble_started_at: enabled ? stateData.sim_time : null,
  });

export function commander(query) {
  const exact = commanderResponses[query];
  if (exact) return delay({ ...exact, is_cached: true });

  const key = Object.keys(commanderResponses).find(
    (q) => q.toLowerCase().includes(query.toLowerCase().slice(0, 12)),
  );
  if (key) return delay({ ...commanderResponses[key], is_cached: true });

  return delay({
    response:
      'No grounded data is available for that question in mock mode. The four scripted questions have recorded answers.',
    is_cached: true,
    tool_calls: [],
    grounding: {
      numbers_emitted: [],
      numbers_grounded: [],
      ungrounded: [],
      ungrounded_count: 0,
      passed: true,
    },
  });
}

export const simulate = (label) =>
  delay({ simulation_id: 'sim_mock1', status: 'running', eta_sec: 2, label });

export const journey = () => delay(journeyData);

// The fixture carries one nudge per segment (att_demo_1/2/3) so export_mocks
// can demonstrate the trade-off for every segment; the real endpoint filters
// by attendee_id and the mock must match, or accepting one attendee's nudge
// silently reveals another attendee's otherwise-identical-looking one.
export const nudges = (attendeeId = 'att_demo_1') =>
  delay({ nudges: nudgeState.nudges.filter((n) => n.attendee_id === attendeeId) });

export function respondToNudge(nudgeId, accepted) {
  const nudge = nudgeState.nudges.find((n) => n.nudge_id === nudgeId);
  if (nudge) nudge.status = accepted ? 'accepted' : 'declined';
  return delay({
    nudge_id: nudgeId,
    status: accepted ? 'accepted' : 'declined',
    compliance_recorded: true,
  });
}

export const overview = () => delay(overviewData);
export const events = () => delay(eventsData);
export const saturation = () => delay(saturationData);
export const disruptions = () => delay(disruptionsData);
export const recommendStay = () => delay(stayData);

/** The recorded fixture, narrowed by the same filters the API accepts. */
export function hotels(params = {}) {
  const items = hotelsData.hotels.filter(
    (h) =>
      (!params.zone || h.zone.toLowerCase() === String(params.zone).toLowerCase()) &&
      (!params.tier || h.tier === params.tier) &&
      (!params.max_price_paise || h.price_per_night_paise <= Number(params.max_price_paise)) &&
      (!params.accessible_only || h.accessible) &&
      (!params.status || h.status === params.status),
  );
  return delay({ ...hotelsData, hotels: items });
}

/** Actions that change the live city cannot be replayed from a recording. */
export function liveOnly() {
  return Promise.reject(
    Object.assign(new Error('This action changes the live city. Start the backend and run `npm run dev:live`.'), {
      code: 'LIVE_ONLY',
    }),
  );
}

export const demoControl = (body) =>
  delay({
    status: body.action === 'pause' ? 'paused' : 'playing',
    sim_time: stateData.sim_time,
    seed: body.seed ?? 42,
    speed_multiplier: body.speed_multiplier ?? 60,
  });

/**
 * Replay the recorded run through the real store actions.
 * Returns a stop function; the caller owns the lifetime.
 *
 * One full pass of the 90-frame recording is one simulation iteration. The
 * per-tick lifecycle — including re-arming the cascade / intervention queue
 * every iteration, not just the first — lives in lib/mockLifecycle.js.
 */
export function startMockDriver(store, { intervalMs = 900 } = {}) {
  let stopped = false;

  store.setMockMode(true);
  store.setWsStatus('connected');

  const ctx = {
    cycle: 0,
    working: null,
    fixtures: {
      stateSequence,
      pressureSequence,
      twinSequence,
      cascadesActive,
      cascadeMetroB,
      interventionsData,
      nudgeData,
    },
  };

  const tick = () => {
    if (stopped) return;
    advanceMockDriver(store, ctx);
    // Keep the mock API's mutable copies pointed at the current iteration's
    // data, so api.approve() / api.nudges() operate on what is on screen now.
    interventionState = ctx.working.interventions;
    nudgeState = ctx.working.nudges;
  };

  tick();
  const handle = setInterval(tick, intervalMs);
  return () => {
    stopped = true;
    clearInterval(handle);
  };
}
